using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Clothing;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Clothing;

[GenerateTypedNameReferences]
public sealed partial class ModsuitGauntletToolsRadialMenu : RadialMenu
{
    private static readonly Dictionary<ModsuitGauntletToolSlot, SpriteSpecifier> MenuIcons = new()
    {
        { ModsuitGauntletToolSlot.Urk, new SpriteSpecifier.Rsi(new ResPath("_Mono/Objects/Tools/repair_device_item.rsi"), "item") },
        { ModsuitGauntletToolSlot.Omnitool, new SpriteSpecifier.Rsi(new ResPath("Objects/Tools/omnitool.rsi"), "omnitool-screwing") },
        { ModsuitGauntletToolSlot.Welder, new SpriteSpecifier.Rsi(new ResPath("Forge/Objects/Tools/Standart/welder_experimental.rsi"), "icon") },
        { ModsuitGauntletToolSlot.NaniteApplicator, new SpriteSpecifier.Rsi(new ResPath("_Mono/Objects/Tools/nanite_applicator_experimental.rsi"), "icon") },
    };

    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private SpriteSystem _sprites = default!;

    public event Action<ModsuitGauntletToolSlot>? OnToolSelected;

    public ModsuitGauntletToolsRadialMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _sprites = _entManager.System<SpriteSystem>();
    }

    public void SetGauntlets(Entity<ModsuitGauntletToolsComponent> gauntlets)
    {
        var main = FindControl<RadialContainer>("Main");
        main.RemoveAllChildren();

        var comp = gauntlets.Comp;

        if (!comp.UrkInHand)
            AddToolButton(main, ModsuitGauntletToolSlot.Urk, comp.UrkProto);

        if (!comp.OmnitoolInHand)
            AddToolButton(main, ModsuitGauntletToolSlot.Omnitool, comp.OmnitoolProto);

        if (!comp.WelderInHand)
            AddToolButton(main, ModsuitGauntletToolSlot.Welder, comp.WelderProto);

        if (!comp.NaniteApplicatorInHand)
            AddToolButton(main, ModsuitGauntletToolSlot.NaniteApplicator, comp.NaniteApplicatorProto);

        if (TryGetActiveSlot(comp, out var activeSlot))
            AddStowButton(main, activeSlot);

        AddToolClickActions(main);
    }

    private void AddToolButton(RadialContainer container, ModsuitGauntletToolSlot slot, EntProtoId protoId)
    {
        if (!_prototypeManager.TryIndex(protoId, out var prototype))
            return;

        var button = new ModsuitGauntletToolsRadialMenuButton
        {
            SetSize = new Vector2(64, 64),
            ToolTip = Loc.GetString(prototype.Name),
            Slot = slot,
        };

        var icon = MenuIcons.GetValueOrDefault(slot);
        var textureSource = icon != null
            ? _sprites.Frame0(icon)
            : _sprites.Frame0(prototype);

        var texture = new TextureRect
        {
            SetSize = new Vector2(48, 48),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Texture = textureSource,
        };

        button.AddChild(texture);
        container.AddChild(button);
    }

    private static bool TryGetActiveSlot(ModsuitGauntletToolsComponent comp, out ModsuitGauntletToolSlot slot)
    {
        if (comp.UrkInHand)
        {
            slot = ModsuitGauntletToolSlot.Urk;
            return true;
        }

        if (comp.OmnitoolInHand)
        {
            slot = ModsuitGauntletToolSlot.Omnitool;
            return true;
        }

        if (comp.WelderInHand)
        {
            slot = ModsuitGauntletToolSlot.Welder;
            return true;
        }

        if (comp.NaniteApplicatorInHand)
        {
            slot = ModsuitGauntletToolSlot.NaniteApplicator;
            return true;
        }

        slot = default;
        return false;
    }

    private void AddStowButton(RadialContainer container, ModsuitGauntletToolSlot slot)
    {
        var button = new ModsuitGauntletToolsRadialMenuButton
        {
            SetSize = new Vector2(64, 64),
            ToolTip = Loc.GetString("modsuit-gauntlet-stow-active"),
            Slot = slot,
        };

        var texture = new TextureRect
        {
            SetSize = new Vector2(48, 48),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Texture = _sprites.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/VerbIcons/fold.svg.192dpi.png"))),
        };

        button.AddChild(texture);
        container.AddChild(button);
    }

    private void AddToolClickActions(RadialContainer container)
    {
        foreach (var child in container.Children)
        {
            if (child is not ModsuitGauntletToolsRadialMenuButton castChild)
                continue;

            castChild.OnButtonUp += _ =>
            {
                OnToolSelected?.Invoke(castChild.Slot);
                Close();
            };
        }
    }
}

public sealed class ModsuitGauntletToolsRadialMenuButton : RadialMenuTextureButtonWithSector
{
    public ModsuitGauntletToolSlot Slot { get; set; }
}
