- type: entity
  id: OreProcessorIndustrialHeavyMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: heavy industrial ore processor machine board
  description: A machine printed circuit board for a heavy industrial ore processor.
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: OreProcessorIndustrialHeavy
    requirements:
      MatterBin: 1
      Manipulator: 4
    stackRequirements:
      Glass: 2

- type: entity
  id: TraumaTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: trauma techfab machine board
  description: A machine printed circuit board for a trauma techfab.
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: TraumaTechFab
      requirements: 
        MatterBin: 2 
        Manipulator: 2 
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker
          
- type: entity
  id: LaserDrillCircuitboard
  parent: BaseMachineCircuitboard
  name: laser drill circuitboard
  description: A machine printed circuit board for a trauma techfab.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: LaserDrill
      requirements: 
        MatterBin: 2 
        Manipulator: 2 